#!/bin/bash
# Event-Driven Microservice Blueprint Generator
# Generates a new microservice with Dapr event handling

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}🔧 Event-Driven Microservice Generator${NC}"
echo "========================================"

# Parse arguments
SERVICE_NAME=""
TOPICS=""
OUTPUT_DIR=""

while [[ $# -gt 0 ]]; do
  case $1 in
    --name)
      SERVICE_NAME="$2"
      shift 2
      ;;
    --topics)
      TOPICS="$2"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# Validate
if [ -z "$SERVICE_NAME" ]; then
  echo "Error: --name is required"
  exit 1
fi

if [ -z "$OUTPUT_DIR" ]; then
  OUTPUT_DIR="./services/$SERVICE_NAME"
fi

echo -e "\n${GREEN}Generating microservice:${NC}"
echo "  Name: $SERVICE_NAME"
echo "  Topics: $TOPICS"
echo "  Output: $OUTPUT_DIR"
echo ""

# Create directory structure
mkdir -p "$OUTPUT_DIR/src"
mkdir -p "$OUTPUT_DIR/dapr"

# Generate main.py
cat > "$OUTPUT_DIR/src/main.py" << EOF
"""
$SERVICE_NAME - Event-Driven Microservice
Generated by: Event-Driven Blueprint Generator
"""

from fastapi import FastAPI, Request
from contextlib import asynccontextmanager

@asynccontextmanager
async def lifespan(app: FastAPI):
    print(f"🚀 Starting $SERVICE_NAME...")
    yield
    print(f"👋 Shutting down $SERVICE_NAME...")

app = FastAPI(
    title="$SERVICE_NAME",
    lifespan=lifespan,
)

@app.get("/health")
async def health():
    return {"status": "healthy", "service": "$SERVICE_NAME"}

@app.get("/dapr/subscribe")
async def dapr_subscribe():
    """Declare Dapr subscriptions."""
    return [
EOF

# Add subscription for each topic
IFS=',' read -ra TOPIC_ARRAY <<< "$TOPICS"
for topic in "${TOPIC_ARRAY[@]}"; do
  cat >> "$OUTPUT_DIR/src/main.py" << EOF
        {
            "pubsubname": "kafka-pubsub",
            "topic": "$topic",
            "route": "/events/$topic",
        },
EOF
done

cat >> "$OUTPUT_DIR/src/main.py" << EOF
    ]

EOF

# Add handler for each topic
for topic in "${TOPIC_ARRAY[@]}"; do
  handler_name=$(echo "$topic" | tr '-' '_')
  cat >> "$OUTPUT_DIR/src/main.py" << EOF
@app.post("/events/$topic")
async def handle_$handler_name(request: Request):
    """Handle events from $topic topic."""
    event = await request.json()
    print(f"[EVENT] Received from $topic: {event}")
    # TODO: Add your event handling logic here
    return {"status": "SUCCESS"}

EOF
done

# Generate Dockerfile
cat > "$OUTPUT_DIR/Dockerfile" << EOF
FROM python:3.13-slim

WORKDIR /app

RUN pip install fastapi uvicorn

COPY src/ ./src/

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
EOF

# Generate Kubernetes deployment
cat > "$OUTPUT_DIR/deployment.yaml" << EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $SERVICE_NAME
  template:
    metadata:
      labels:
        app: $SERVICE_NAME
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "$SERVICE_NAME"
        dapr.io/app-port: "8000"
    spec:
      containers:
        - name: $SERVICE_NAME
          image: $SERVICE_NAME:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
spec:
  selector:
    app: $SERVICE_NAME
  ports:
    - port: 8000
      targetPort: 8000
EOF

echo -e "\n${GREEN}✅ Microservice generated!${NC}"
echo ""
echo "Next steps:"
echo "  1. cd $OUTPUT_DIR"
echo "  2. docker build -t $SERVICE_NAME:latest ."
echo "  3. kubectl apply -f deployment.yaml"
echo ""
echo "Files created:"
ls -la "$OUTPUT_DIR"
